service: qrcoded-lambda

provider:
  name: aws
  runtime: nodejs12.x

layers:
  modules:
    path: layers/modules

functions:
  generateQrcode:
    handler: functions/generate-qr-code.handle
    layers:
      - { Ref: ModulesLambdaLayer }
    events:
      - http:
          path: /qrcodes/generate
          method: post
